<?php

if (php_sapi_name() === 'cli') {
    if ($argc < 2) {
        echo "Usage: {$argv[0]} <path_to_db>\n";
        die;
    }
    $pathToDb = $argv[1];
} else {
    $pathToDb = $_REQUEST['db'];
}

$DIR = dirname(__FILE__);
require "$DIR/../src/classes/Database.php";

$db = new Database($pathToDb);
$history = $db->getHistory();
$listeners = $db->getListeners();

?>

<!DOCTYPE html>
<html class="page"
      lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="color-scheme" content="light dark">
        <!--    <link rel="icon" type="image/png" href="data:image/png;base64,">-->
        <title>Radio stats</title>

        <link rel="preload stylesheet"
              as="style"
              href="/styles.css"
              type="text/css"
              fetchpriority="high"
              referrerpolicy="no-referrer"
              crossorigin="anonymous">

        <link rel="preload"
              as="script"
              href="https://cdn.jsdelivr.net/npm/chart.js"
              type="text/javascript"
              crossorigin="anonymous">
    </head>

    <body class="center"
          style="--gutters: var(--s0);">

        <div id="chart-legend"></div>

        <div class="frame"
             style="--n: 16, --d: 9">

            <canvas id="chart"></canvas>
        </div>

        <h2>Latest tracks</h2>

        <!-- TODO(toby3d): make vertical timeline with >20 latest played tracks for all stations? 3-column table is too wide for mobile screens and hard to understand. :\ -->
        <table>
            <tr>
                <!-- TODO(toby3d): generate columns and take it's names from data.datasets[].label -->
                <th>
                    <a href="https://sovietwave.su" target="_blank">
                        Sovietwave
                    </a>
                </th>
                <th>
                    <a href="https://provoda.ch" target="_blank">
                        Provoda.ch
                    </a>
                </th>
                <th>
                    <a href="https://witch.waveradio.org/" target="_blank">
                        Witch House
                    </a>
                </th>
            </tr>
            <?php for ($entry = 0; $entry < 20; $entry++): ?>
                <tr>
                    <td>
                        <a target="_blank" href="https://youtube.com/results?<?= http_build_query(['search_query' => "{$history['soviet'][$entry]['artist']} {$history['soviet'][$entry]['title']}"]) ?>">
                            <h3>
                                <?= $history['soviet'][$entry]['artist'] ?>
                            </h3>
                            <?= $history['soviet'][$entry]['title'] ?>
                        </a>
                    </td>
                    <td>
                        <a target="_blank" href="https://youtube.com/results?<?= http_build_query(['search_query' => "{$history['provodach'][$entry]['artist']} {$history['provodach'][$entry]['title']}"]) ?>">
                            <h3>
                                <?= $history['provodach'][$entry]['artist'] ?>
                            </h3>
                            <?= $history['provodach'][$entry]['title'] ?>
                        </a>
                    </td>
                    <td>
                        <a target="_blank" href="https://youtube.com/results?<?= http_build_query(['search_query' => "{$history['witch'][$entry]['artist']} {$history['witch'][$entry]['title']}"]) ?>">
                            <h3>
                                <?= $history['witch'][$entry]['artist'] ?>
                            </h3>
                            <?= $history['witch'][$entry]['title'] ?>
                        </a>
                    </td>
                </tr>
            <?php endfor; ?>
        </table>

        <footer>
            Fork it <a href="https://github.com/xxkfqz/radiostat" target="_blank">here</a>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"
                async></script>
        <script>
            const labels = [<?= implode(',', array_map(function ($date) { return "'$date'"; }, array_keys($listeners['provodach']))) ?>];
            <?php foreach ($listeners as $code => $values): ?>
                const data_<?= $code ?> = [<?= implode(',', array_values($values)) ?>];
            <?php endforeach; ?>

            const data = {
                labels: labels,
                datasets: [
                    {
                        label: 'Provoda.ch',
                        data: data_provodach,
                        borderColor: '#610298',
                        fill: false,
                        tension: 0.4
                    },
                    {
                        label: 'Sovietwave',
                        data: data_soviet,
                        borderColor: '#e0c200',
                        fill: false,
                        tension: 0.4
                    },
                    {
                        label: 'Witch House',
                        data: data_witch,
                        borderColor: '#0013d3',
                        fill: false,
                        tension: 0.4
                    }
                ]
            };
            const config = {
                type: 'line',
                data: data,
                options: {
                    responsive: true,
                    plugins: {
                        title: {
                            display: true
                        }
                    },
                    interaction: {
                        intersect: false
                    },
                    scales: {
                        x: {
                            display: true,
                            title: {
                                display: true
                            }
                        },
                        y: {
                            display: true,
                            title: {
                                display: true,
                                text: 'Listeners'
                            },
                            suggestedMin: 0
                            // suggestedMax: 200
                        }
                    }
                }
            };

            new Chart(document.getElementById('chart'), config);
        </script>
    </body>
</html>
